# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test ./Durable.Mstest/ --logger trx --collect "Code coverage"
  displayName: 'dotnet test'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
#- script: dotnet publish --output $(Build.ArtifactStagingDirectory)
 # displayName: 'dotnet publish $(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: False
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
   # pathtoPublish: $(Build.ArtifactStagingDirectory) 
   # artifactName: 'drop' 
   # publishLocation: 'filePath'
   # targetPath: 'D:\a\r1\a\'

    
